//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWaiTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int PriceListId { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string Title { get; set; }
        public int MasterId { get; set; }
        public bool Visited { get; set; }
        public bool Payed { get; set; }
        public Nullable<int> BuyId { get; set; }
        public Nullable<double> BuyPrice { get; set; }
    
        public virtual Buy Buy { get; set; }
        public virtual Master Master { get; set; }
        public virtual PriceList PriceList { get; set; }
    }
}
